`with_shutdown` for Tokio app
w-henderson/Humphrey pull request #113
Opened 2024-01-04 03:30 UTC by Grinkers

I don't do much rust async. I find it overly annoying for little benefit. One of the reasons I found this crate was it's one of the few that don't have page long dependency trees, super simple, and low-latency.

I pulled in https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html
which is part of the tokio project https://github.com/tokio-rs/tokio/tree/master/tokio-util
as I think this might be exactly what we're looking for.

2024-01-04 12:58 UTC, w-henderson requested changes
Looks very good and concise, just a little thing to look at.

2024-01-04 12:58 UTC, w-henderson commented on humphrey/src/tokio/app.rs
> +                        let _ = tokio::time::sleep(std::time::Duration::from_secs(9999));
If you're trying to express "future that never resolves" you should use [`future::pending`](https://docs.rs/futures/latest/futures/future/fn.pending.html) I think.

2024-01-04 13:00 UTC, w-henderson commented
For what it's worth, I don't do much Rust async either, but I thought it would be good for people to have the option of using Humphrey with the whole Tokio ecosystem. For example, it was particularly awkward (near impossible) to use it with lots of database connection crates that rely heavily on async before I added the Tokio feature.

2024-01-05 00:29 UTC, Grinkers commented
> For what it's worth, I don't do much Rust async either, but I thought it would be good for people to have the option of using Humphrey with the whole Tokio ecosystem. For example, it was particularly awkward (near impossible) to use it with lots of database connection crates that rely heavily on async before I added the Tokio feature.

Ah, that makes a lot of sense. I was wondering why adding the bloat/dependencies when it goes against the default case.

I pushed with `future::pending` and marked ready for review.

2024-01-05 11:50 UTC, w-henderson requested changes

2024-01-05 11:50 UTC, w-henderson commented on humphrey/src/tokio/app.rs
> +                if let Some(sd) = self.shutdown.clone() {
Can we change the `.clone()` to `.as_ref()`? Just to avoid the unnecessary allocation.

2024-01-05 11:58 UTC, Grinkers commented
CI ran too! Nice.

2024-01-05 12:22 UTC, w-henderson approved these changes
Great, thank you so much for all your work on this!

2024-01-05 12:22 UTC, merged